---
title: "Other R resources"
output:
  html_document:
    number_sections: false
    toc: true
    toc_float: 
      collapsed: no
---

# Websites

The internet is filled with R resources. (Case in point, this website!) Here are a few non-obvious ones to new users:

* [CRAN Task View: Econometrics](https://cran.r-project.org/web/views/Econometrics.html). An encyclopedia of R functions and packages for econometrics.
* [Stack Overflow](https://stackoverflow.com/questions/tagged/r). A free Q&A website for coding questions. Possibly one of the most valuable public goods on the internet. 
* [TidyTuesday](https://github.com/rfordatascience/tidytuesday). New and interesting data sets released every week by the people who made the tidyverse. 
* Follow the latest R developments on Twitter using the hashtag [#rstats](https://twitter.com/hashtag/rstats?lang=en) 

# Packages

There are over [17,000 packages and counting](https://lrdegeest.github.io/blog/totalverse) on the CRAN network. Fortunately you can get by with just a few. Here are some to consider. 

## Analysis

Alongside the tidyverse, here are some useful packages for econometrics. 

* [`sjPlot`](https://strengejacke.github.io/sjPlot/) for regression tables and regression plots. If you just want to generate predictions from regression models check out [`ggeffects`](https://strengejacke.github.io/ggeffects/) (an input to `sjPlot`).
  - Another great package for model visualization is [`modelsummary`](https://vincentarelbundock.github.io/modelsummary/index.html)
  - [`broom`](https://broom.tidymodels.org/) is a great package for "tidying" model results into data frames.
* [`patchwork`](https://patchwork.data-imaginist.com/) for combining multiple `ggplot` objects into one figure.
* [`plm`](https://cran.r-project.org/web/packages/plm/plm.pdf) for panel data econometrics.
* [`lmtest`](https://cran.r-project.org/web/packages/lmtest/index.html) for coefficient tests on linear models. You can combine this with [`sandwhich`](https://cran.r-project.org/web/packages/sandwich/sandwich.pdf) to cluster standard errors.
* [`forecast`](https://cran.r-project.org/web/packages/forecast/index.html) for time series econometrics.
* [`fixest`](https://cran.r-project.org/web/packages/fixest/vignettes/fixest_walkthrough.html) for linear models with fixed effects and clustering.

There is also [`tidymodels`](https://www.tidymodels.org/) a collection of packages for econometrics and machine learning.

## Data

* [`fabricatr`](https://declaredesign.org/r/fabricatr/) for simulating fake data.
* [`fredr`](https://cran.r-project.org/web/packages/fredr/index.html) gives you access to the FRED (Federal Reserve Bank of St. Louis) database. [`tidyquant`](https://business-science.github.io/tidyquant/) provides access to Yahoo Finance and other financial data sources. 
* [`fivethirtyeight`](https://cran.r-project.org/web/packages/fivethirtyeight/vignettes/fivethirtyeight.html) provides over 100 data sets featured on the sports/politics/etc. blog [fivethirtyeight](https://fivethirtyeight.com/).
* [`wbstats`](https://cran.r-project.org/web/packages/wbstats/wbstats.pdf) for World Bank data.
* [`ipumsr`](http://tech.popdata.org/ipumsr/articles/ipums.html) for [IPUMS](https://ipums.org/) census and survey data. 
* [`Lahman`](https://cran.r-project.org/web/packages/Lahman/) provides access to a wide variety of baseball data.
* Access Twitter data (tweets, etc.) with [`rtweet`](https://cran.r-project.org/web/packages/rtweet/index.html).
* [`tidycensus`](https://walker-data.com/tidycensus/) for U.S. Census data.
* [`nhanesA`](https://cran.r-project.org/web/packages/nhanesA/vignettes/Introducing_nhanesA.html) provides access to National Health and Nutrition Examination Survey (NHANES).
* [`Ecdat`](https://cran.r-project.org/web/packages/Ecdat/Ecdat.pdf) for a bunch of other econometrics data sets. 

Check out [Awesome Public Datasets](https://github.com/awesomedata/awesome-public-datasets) for other datasets on economics and much more. 

# Books

* [R for Data Science](https://r4ds.had.co.nz/) is the standard introductory text to data science with R and the tidyverse. If you only work through one book, make it this one.
* [Modern Dive](https://moderndive.netlify.app/index.html) is another (and longer) introduction to R and the tidyverse.
* [Econometrics with R](https://www.econometrics-with-r.org/) is a great text for econometrics (though it does not use the tidyverse).
* [Advanced R](https://adv-r.hadley.nz/). For advanced users who really want to hone their skills. 
* [R Markdown Definitive Guide](https://bookdown.org/yihui/rmarkdown/). The definitive guide! 

# Cheatsheets

* [R Markdown](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
* [`dplyr`](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)
* [`ggplot2`](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
* [More cheatsheets!](https://www.rstudio.com/resources/cheatsheets/)

# Job Market Signaling

You have the skills. But anybody can write the letter "R" on their resume. So how do you separate from the pack? Here are two ideas:

* Build a personal website entirely in R Studio using [blogdown](https://bookdown.org/yihui/blogdown/). The website itself is a *credible* signal (costly for anyone produce, and costlier for those less skilled). You can also post your senior thesis (along with an executive summary) and class projects to showcase your work! Here is a [demo](https://jon-snow-targaryen.netlify.app/) we built in about one hour during a department workshop in Spring 2020 (thanks to this excellent [Twitter thread](https://twitter.com/dsquintana/status/1139846569623281664?lang=en)). 
* Post your code on [GitHub](https://github.com/), the leading platform on the internet for open source software. 