---
title: "Notebooks"
output:
  html_document:
    number_sections: false
    toc: true
    toc_float: 
      collapsed: no
---

# What is a notebook? 

Scripts only let you write code and comments. Notebooks let you write code and text -- headers, paragraphs, etc. -- in the same document. By default they render into an easy-to-read HTML document. 

Notebooks always have the `.Rmd` extension (e.g., `notebook.Rmd`.)

# Creating a notebook

"File -> New File -> R Notebook". A demo notebook will pop up. Delete the demo text and code and start writing/coding!

## Video

<br>
<center>
<iframe src="https://suffolku.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b0fdb687-ab71-4206-9e39-ad1801629697&autoplay=false&offerviewer=true&showtitle=false&showbrand=false&start=0&interactivity=all" height="405" width="80%" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>
</center>
<br>

# Working in a notebook

There are three parts to a notebook:

1. YAML (formatting the document)
2. Text (writing)
3. Code chunks (coding)

You can then render the notebook to an HTML file.

### YAML

The stuff at the top in between the `---`. The default is:

```
---
title: "R Notebook"
output: html_notebook
---
```

You can change the title and add an author:

```
---
title: "My title"
author: "First Last"
output: html_notebook
---
```

and that suffices for a basic notebook. For more options see [the Markdown checkpoint](https://suffolkecon.github.io/markdown.nb.html#2_YAML).

### Text

Write plain text in [Markdown](https://suffolkecon.github.io/markdown.nb.html).

### Code chunks

Code gets entered in "chunks" -- the highlight boxes with "fences" (three open and closed backticks). 

### Rendering a notebook

Click on "Preview notebook" to see the rendered HTML document. 

Every time you change the file and save it, the document will re-render. 

All notebooks are saved with `.Rmd` extension. After you render the notebook, in your files you will see a new file with the extension `.nb.html`. So iff your notebook is called `notebook.Rmd`, the rendered file is called `notebook.nb.html`.

### Video

<br>
<center>
<iframe src="https://suffolku.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=0485d049-fcc6-4d67-a5e7-ad1801635f2a&autoplay=false&offerviewer=true&showtitle=false&showbrand=false&start=0&interactivity=all" height="405" width="80%" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>
</center>
<br>


# R Markdown

R Notebooks are part of a much bigger document ecosystem driven by R Markdown. 

R Markdown lets you turn the same document into a HTML, Microsoft Word, PowerPoint, or PDF. 

Learn more at the [official R Markdown site](https://rmarkdown.rstudio.com/) and the [definitive guide](https://bookdown.org/yihui/rmarkdown/).

Here is the notebook rendered (or "knitted") to a Word file:

<br>
<center>
<iframe src="https://suffolku.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=18f1016b-0bc7-476d-816c-ad180163d6dc&autoplay=false&offerviewer=true&showtitle=false&showbrand=false&start=0&interactivity=all" height="405" width="80%" style="border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>
</center>
<br>
